version: "3"

services:
  backend:
    build: .
    command: bash -c "python project/manage.py runserver 0.0.0.0:8000"
    container_name: cookbook_backend
    restart: unless-stopped
    volumes:
      - .:/cookbook
    ports:
      - 8000:8000
    env_file: ./src/project/.env
    depends_on:
      - database
  database:
    image: postgres:alpine
    container_name: cookbook_database
    env_file: ./src/project/.env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database:
